name: Test and Release
on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/release.yaml'
    branches: [main, master]
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/release.yaml'
    branches: [main, master]

permissions:
  contents: read

jobs:
  e2e-tests:
    name: Run E2E tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: npm ci
      - name: Run tests
        env:
          AUTH1: ${{ secrets.AUTH1 }}
          AUTH2: ${{ secrets.AUTH2 }}
          MERCHANT_ID: ${{ secrets.MERCHANT_ID }}
          AZUL_KEY: ${{ secrets.AZUL_KEY }}
          AZUL_CERT: ${{ secrets.AZUL_CERT }}
        run: npm run test

  release:
    name: Release
    needs: [integration-tests, e2e-tests]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures
        run: npm audit signatures
      - name: Build
        run: npm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
